/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "HtmlPdfApp": {
      "type": "sst.aws.SolidStart"
      "url": string
    }
    "HtmlPdfAuth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "HtmlPdfConverter": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "HtmlPdfEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "HtmlPdfRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "HtmlPdfStorage": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}